# Generated by Django 5.0 on 2024-10-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_profile_img_jobseekerprofile_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='resume',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='Place',
            field=models.TextField(blank=True),
        ),
    ]
