# Generated by Django 5.0 on 2024-10-20 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_jobseekerprofile_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=250)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager')], default='admin', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='Place',
            new_name='place',
        ),
    ]
