# Generated by Django 5.0 on 2024-11-18 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_otpverification_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerotpverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
