# Generated by Django 5.1.2 on 2025-01-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('jobseeker', 'Jobseeker'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
