# Generated by Django 5.1.2 on 2024-12-10 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_user_type'),
        ('interview', '0002_alter_interview_applicant_alter_interview_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='api.jobseekerprofile'),
        ),
    ]
