# Generated by Django 5.1.2 on 2024-12-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_interview_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='applicant',
        ),
        migrations.AddField(
            model_name='interview',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
