# Generated by Django 5.1.2 on 2024-12-11 18:24

import interview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_remove_interview_applicant_interview_applicant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[interview.models.validate_custom_url]),
        ),
    ]
