# Generated by Django 5.0 on 2024-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.AddField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='JobSkill',
        ),
    ]
