# Generated by Django 5.0 on 2024-10-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_delete_jobcategory_remove_job_skills_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applications_count',
        ),
        migrations.RemoveField(
            model_name='job',
            name='views_count',
        ),
    ]
