# Generated by Django 5.0 on 2024-10-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
    ]
