# Generated by Django 5.0 on 2024-11-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_jobapplication_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
