# Generated by Django 5.1.2 on 2024-12-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
